version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static-data:/vol/web
    env_file:
      - .env
    build:
      context: .
    restart: unless-stopped  
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static-data:/vol/static
      - ./www-certs:/etc/letsencrypt
    env_file: .env
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django_gunicorn

volumes:
  static-data:
